### ISSUE TITLE
Illegal division by zero at  pull_task() stats 

### ISSUE THREAD

**Issue by srikanth007m** [yangoliver/mytools#1]
I am using your script for parsing /proc/sched_stat o/p to debug some scheduler issues. pull_task() is showing Illegal division by zero at stats-15.pl line 607, <> line 4733.

**Comment by yangoliver** [comment]
Hi Srikanth007m,

You may used a incomplete version. I just finished the work 3 days ago.

Have you tried below commit?

```
commit ddb7322b97269ef2f7b2db847141fa3542c07ded
```

Another thing is related to the script usage,

You need got two snapshots for /proc/schedstat first.

The run below command,

```
 stats-15.pl -tcd <snap_shot1> <snap_shot2>
```

**Comment by srikanth007m** [comment]
Yes, The script which i am trying is having the above commit-id. I just used the same command but not with options "cd".

**Comment by yangoliver** [comment]
srikanth007m,

Could you tell me which Linux kernel version you used? This script only works for v15 schedstat.

This is my output on my Linux box.

```
# ./stats-15.pl -t /proc/schedstat  /proc/schedstat
00:00:00--------------------------------------------------------------
      0          sys_sched_yield()

     32          schedule()
     14( 43.75%) scheduled no process (left cpu idle)


     18          try_to_wake_up()
     18(100.00%) task being awakened was last on same cpu as waker
8112.33/2495.94    avg runtime/latency over all cpus (ns)

      0          tasks pulled by pull_task()

     70          load_balance()
     28( 40.00%) called while idle
                      24( 85.71%) found no busier group
                       4( 14.29%) succeeded in moving at least one task
                                  (average imbalance:   0.000)
      0(  0.00%) called while busy
     42( 60.00%) called when newly idle
                       4(  9.52%) tried but failed to move any tasks
                      38( 90.48%) found no busier group

      0          active_load_balance() was called
```

**Comment by yangoliver** [comment]
Please provide your kernel version.

I think the root cause of you bug is, the PT_HOT_IDLE is not zero, but the total pull task count is zero.
This is an impossible case, kernel code always ensure this case won't happen.

I just add one line debug code to ensure my analysis, could you possibly to run it?

```
$ git diff
diff --git a/cpu/schedstat/stats-15.pl b/cpu/schedstat/stats-15.pl
index 3832c4b..04d71a7 100644
--- a/cpu/schedstat/stats-15.pl
+++ b/cpu/schedstat/stats-15.pl
@@ -604,6 +604,7 @@ sub print_diffs {
        $pt_cnt_total = $domain_diff_all[$PT_CNT_IDLE] +
            $domain_diff_all[$PT_CNT_NEWIDLE] + $domain_diff_all[$PT_CNT_NOIDLE];
        printf "    %7d          tasks pulled by pull_task()\n", $pt_cnt_total;
+       printf "debug PT_HOT_IDLE: %7d, pt_cnt_total: %7d", $domain_diff_all[$PT_HOT_IDLE], $pt_cnt_total;
        printf "    %7d(%6.2f%%) pulled from hot cpu while still cache-hot and idle\n",
            $domain_diff_all[$PT_HOT_IDLE],
            100*$domain_diff_all[$PT_HOT_IDLE]/$pt_cnt_total
```

If the root cause could be confirmed, please send me your raw data of /proc/schedstat.

If raw data had the same problem, I think it is kernel bug. Otherwise, my parsing should have the bug.

**Comment by srikanth007m** [comment]
My Kernel version 

```
Linux smuppand-linux 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
/proc/schedstat
version 15
```

Definitely i will give it a try and let you know. Also can you add an enhancement for calculating latency for runtime and runnable time.? or any existing script which can parse from ftrace will also be helpful

**Comment by yangoliver** [comment]
Hi srikanth007m,

You version looked good. I will wait for your debug output.

For CPU run time and scheduling latency, the script already supports it.

Please use -tc to get the average CPU runtime and latency,  

   # ./stats-15.pl -tc /proc/schedstat  /proc/schedstat

```
[output snipped .....]
5392.00/0.00      avg runtime/latency on cpu 0 (ns)
7426.00/1045.00    avg runtime/latency on cpu 1 (ns)
7902.00/1062.50    avg runtime/latency on cpu 3 (ns)
8186.00/1392.00    avg runtime/latency on cpu 4 (ns)
12445.00/4475.33    avg runtime/latency on cpu 5 (ns)
5531.00/0.00      avg runtime/latency on cpu 7 (ns)
7089.00/1461.00    avg runtime/latency on cpu 10 (ns)
7418.00/1058.00    avg runtime/latency on cpu 12 (ns)
18859.50/2152.00    avg runtime/latency on cpu 13 (ns)
8865.00/2182.00    avg runtime/latency on cpu 14 (ns)
37618.50/11605.50    avg runtime/latency on cpu 15 (ns)
15929.00/2651.00    avg runtime/latency on cpu 18 (ns)
15564.00/1165.00    avg runtime/latency on cpu 22 (ns)
6686.00/0.00      avg runtime/latency on cpu 24 (ns)
7738.00/1232.00    avg runtime/latency on cpu 27 (ns)
13095.95/2762.60    avg runtime/latency over all cpus (ns)
```

**Comment by srikanth007m** [comment]
The script is based on /proc/schedstat and it refers per CPU wise runtime latency as expected. But what i am trying to see is from per process wise. Which can't be done from schesdstat and that needs ftrace logs to figure out.

**Comment by yangoliver** [comment]
srikanth007m,

The /proc/schedstat is designed for system wide.

For per-task level, you can use /proc/<pid>/schedstat.

Below tool I ported from community can work on that,

```
  https://github.com/yangoliver/mytools/blob/master/cpu/schedstat/latency.c
```

However, this tool still has the bugs on time display, I will take more time to fix them.

If your tasks are CFS tasks instead other scheduling class, you can use /proc/<pid>/sched as well.

```
 The scheduling latency could be  se.statistics.wait_sum / se.statistics.wait_count.
```

Here is an example in my system,

```
# cat /proc/100/sched
ksoftirqd/21 (100, #threads: 1)
---------------------------------------------------------
se.exec_start                      :     654888263.691683
se.vruntime                        :       1150779.315670
se.sum_exec_runtime                :           356.127446
se.statistics.wait_start           :             0.000000
se.statistics.sleep_start          :     654888263.691683
se.statistics.block_start          :             0.000000
se.statistics.sleep_max            :       1600053.206664
se.statistics.block_max            :           182.602050
se.statistics.exec_max             :             0.228358
se.statistics.slice_max            :             0.228358
se.statistics.wait_max             :            35.957879
se.statistics.wait_sum             :         79874.644687 >>>> wait time sum in queue
se.statistics.wait_count           :                22484        >>>> wait count
se.statistics.iowait_sum           :             0.000000
se.statistics.iowait_count         :                    0
```

**Comment by srikanth007m** [comment]
Thanks for your information. This helps me in a better manner. Also now the parser is also working fine. There seems some problem with my schedstat output.

**Comment by srikanth007m** [comment]
The latency is not showing the avgruntime for the selected process. 

```
7019 (top) avgrun=270873.32ms avgwait=17002.12ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=326294.23ms
7019 (top) avgrun=0.00ms avgwait=10965.76ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=17625.60ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=16473.18ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=16088.86ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=15978.30ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=45552.20ms
7019 (top) avgrun=0.00ms avgwait=17559.21ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=15475.28ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=16531.80ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=15649.55ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=319161.30ms
7019 (top) avgrun=0.00ms avgwait=13100.35ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=13464.44ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
7019 (top) avgrun=0.00ms avgwait=16461.38ms
7019 (top) avgrun=0.00ms avgwait=0.00ms
```

**Comment by yangoliver** [comment]
I guess there is no bug here.

zero avgrun means no runtime increase in /proc/<pid>/schedstat during that time interval.

```
./latency -v <pid> could give your more debug output.
```

In /proc/<pid>/schedstat file, there are 3 fields. The first field is the runtime.

If runtime always kept unchanged, that means your process had never been scheduled on CPU.

**Comment by yangoliver** [comment]
BTW, the latency.c had wrong time unit in output.

In fact, the it is not millisecond, it should be nanosecond. So ms is not correct, it should be ns.

**Comment by srikanth007m** [comment]
How to debug the output of latency with respect to scehdstat.. With help of runtime and waittime

**Comment by yangoliver** [comment]
You should know whether the scheduling latency is good or bad first.

If you are using latency.c against your application, you need care about avgwait value.

In your above output, the scheduling latency of your process is from 13 to 326 us, does that meet your requirements?

If you have no idea of your requirements, you should find a baseline as a start point.

If the process is not a real time process, this level of latency is good enough.

**Comment by yangoliver** [comment]
BTW, I did another commit to fix time unit problem in latency.c.

**Comment by srikanth007m** [comment]
Quite confusing on debugging to predict what will be the baseline to start profiling the scheduling latency. 

You are right, i might need to check the process is real time or not. I will make sure to run the program in real time with highest priority to check the variance.

**Comment by srikanth007m** [comment]
I've tried the latest changes.. Now the o/p is entirely different. It would be great if you can print name of the each column. 

```
./latency -v 23953
23953 (chrome) 2147483647(2147483647) 2147483647(2147483647) 3379659(3379659) 635.41 635.41
23953 (chrome) 2147483647(0) 2147483647(0) 3379690(31) 0.00 0.00
23953 (chrome) 2147483647(0) 2147483647(0) 3379720(30) 0.00 0.00
23953 (chrome) 2147483647(0) 2147483647(0) 3379751(31) 0.00 0.00
23953 (chrome) 2147483647(0) 2147483647(0) 3379785(34) 0.00 0.00
23953 (chrome) 2147483647(0) 2147483647(0) 3379817(32) 0.00 0.00
23953 (chrome) 2147483647(0) 2147483647(0) 3379847(30) 0.00 0.00
23953 (chrome) 2147483647(0) 2147483647(0) 3379880(33) 0.00 0.00
23953 (chrome) 2147483647(0) 2147483647(0) 3379910(30) 0.00 0.00
23953 (chrome) 2147483647(0) 2147483647(0) 3379942(32) 0.00 0.00
23953 (chrome) 2147483647(0) 2147483647(0) 3379970(28) 0.00 0.00
23953 (chrome) 2147483647(0) 2147483647(0) 3379996(26) 0.00 0.00
23953 (chrome) 2147483647(0) 2147483647(0) 3380027(31) 0.00 0.00
```

**Comment by yangoliver** [comment]
From your verbose output, that is clear that your chrome process never get scheduled by CPU during certain time period.

That is why you got zero avgrun time. It is reasonable, as chrome is kind of IA type process instead of computing bound process.

I didn't see any problems here.

**Comment by yangoliver** [comment]
BTW, the output differences are caused by -v option instead of my latest fix.

The -v is for debugging, and you can switch back to original usage without using -v.

**Comment by srikanth007m** [comment]
Can you help me in understanding on how you are justifying the scheduling latency of the process starts from x to x1 ns from previous to previous latency output.

**Comment by yangoliver** [comment]
The avgwait=13100.35ms means the latency of waiting on the run queue is 13100.35ns, then it should be about 13 us. 

The avgwait=326294.23ms means the latency of waiting on the run queue is avgwait=326294.23ns, then it should be about 326 us.

The ms here is a bug, so the right unit should be ns. New version has changed the ms output with ns output.

**Comment by srikanth007m** [comment]
Yes, i have checked out the latest snapshot. 

How about the avgruntime and the combination of both to conclude the latency issue. Sorry to bother to for simple questions. Is it possible to explain with some realtime process and also with not.

**Comment by yangoliver** [comment]
avgruntime is CPU run time, the avgwait is the process waiting on the run queue.

When a sleep process got waken up, it must be put on the per CPU run queue first. So the avgwait means the latency between process ready for run to running on CPU.

If avgruntime is high, that means the process is always running on the CPU, which is good for performance. 

So only avgwait is a bad thing.

However, the code latency has two parts, run queue wait time and sleep time.

If you didn't see high avgruntime for your process, you need check both run queue wait time (avgwait) and sleep time.

**Comment by srikanth007m** [comment]
In that case these are with respect to process queuing. I am wondering where the current logic helps in a big.little arch CPUs.. where the big process should always be placed in big cpus for better performance.

**Comment by yangoliver** [comment]
I can't understand your question here.

Without CPU run queue design, OS couldn't let multiple processes to share the CPU, at same time, each processes just thought only itself is using this CPU.

This is a common design for all of current OSes, like Linux, Solaris, Windows.

But OS does provide the ways to let one important process use more CPU share than others.
This is why real time process and process priority concepts got created.

**Comment by srikanth007m** [comment]
Just check the ARM big.Little arch. where the process will be placed on big /little cluster based on task https://www.arm.com/products/processors/technologies/biglittleprocessing.php

**Comment by yangoliver** [comment]
What I learned from community for ARM big.Little arch support is, arch community had a private patch which allows scheduler to dispatch tasks/processes per their workload. That means, important tasks could be dispatched to the core has the good performance.

I'm not sure whether your kernel has the patch or not. But at least you can leverage CPU affinity setting to make sure your known tasks are bound to performance optimized cores.

**Comment by srikanth007m** [comment]
I am using Linaro LSK on ARM bigLittle arch only. You mean with existing script that can be done to know whether the tasks is being placed on big cluster if it is a performance core?
